from building import *
Import('rtconfig')

src   = []
cwd   = GetCurrentDir()

# add ads1146 src files.
if GetDepend('PKG_USING_ADS1146'):
    src += Glob('src/ads1146.c')

# add ads1146 include path.
path  = [cwd + '/src']

# add src and include to group.
group = DefineGroup('ads1146', src, depend = ['PKG_USING_ADS1146'], CPPPATH = path)

Return('group')
